export const JOIN_SESSION = "JOIN_SESSION";
export const RESET_SESSION = "RESET_SESSION";
export const SET_ROOM_ID = "SET_ROOM_ID";

export const WS_UPDATE_CONNECTION_STATE = "WS_UPDATE_CONNECTION_STATE";
export const WS_ACTION = "WS_ACTION";
export const WS_USERSLIST = "WS_USERSLIST";
